### ISSUE TITLE
La fonction de suppression des thèmes n'est pas bonne

### ISSUE THREAD

**Issue by abdounasser202** [proxima-cm/IslamApp#18]
@elmaroufa la fonction de suppression des thèmes n'est pas bonne. 

Il s'agit de la fonction `delete_theme()` à la ligne 142 que tu peux voir ici: https://github.com/proxima-cm/IslamApp/blob/nasser/application/plugins/theme/controllers/theme_controller.py#L142

En effet, le `delete` se fait en mode `GET`. Du coup, tu n'a pas besoin de passer l'argument `POST` dans ton `router` et tu n'a pas besoin de faire de vérification sur le type de méthode que te renvoie ton controlleur. En gros, tu dois écrire un truc simple comme celui que j'ai implémenté dans la fonction `delete_coordinates` que tu peux retrouver ici: https://github.com/proxima-cm/IslamApp/blob/nasser/application/plugins/geotime/controllers/geo_ctrl.py#L78

```
@app_geotime.route('/delete/coordinates/<int:id>')
def delete_coordinates(id):
    place = PlaceModel.query.filter_by(id=id).first()
    db.session.delete(place)
    db.session.commit()
    return redirect(url_for('geotime.list_coordinates'))
```

**Comment by elmaroufa** [comment]
c'est bon, problème résolue

**Comment by abdounasser202** [comment]
très bien, merci d'avoir fermé ce ticket
